# -*- coding: utf-8 -*-
"""CC.PROJET ANALYSE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJqEoRSsUmhX8rMBxO2WoKlyA_leVZga
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
df=pd.read_csv('/content/drive/MyDrive/Préparation examen/ANALYSE YouTube Tech Channels Statistics 2025/youtube_tech_channels_20251120_133753.csv')
df



"""# Task
Analyze the YouTube tech channels dataset `df` by understanding its structure, cleaning and preparing the data, identifying top channels based on subscribers and views, analyzing channel creation trends, examining video count and country distributions, and exploring correlations between key metrics, then summarize the key insights.

## Understand Dataset Structure

### Subtask:
Display the first few rows, data types, and summary statistics of the DataFrame to get an initial understanding of the data.

**Reasoning**:
To get an initial understanding of the dataset, I will display the first few rows, check the data types and non-null counts, and view the descriptive statistics of the numerical columns using `df.head()`, `df.info()`, and `df.describe()` respectively.
"""

print("First 5 rows of the DataFrame:")
print(df.head())

print("\nDataFrame Info (data types and non-null values):")
df.info()

print("\nDescriptive statistics of numerical columns:")
print(df.describe())

"""## Clean and Prepare Data

### Subtask:
Convert the 'created_date' column to datetime objects for time-series analysis and check for any duplicate entries.

To prepare the data for time-series analysis, I will convert the `created_date` column to a datetime format. Additionally, I will check for and quantify any duplicate rows in the dataset to ensure data integrity.

**Reasoning**:
Now I will convert the 'created_date' column to datetime objects and then check for duplicate rows in the DataFrame.
"""

df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce')

# Check for duplicate entries
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

"""## Top Channels Analysis (Subscribers & Views)

### Subtask:
Identify and visualize the top 10 channels based on their subscriber count and total views. This will include bar charts for both metrics.

**Reasoning**:
I will identify the top 10 channels by subscribers, create a bar plot for them, then identify the top 10 channels by total views, and create another bar plot. Both plots will be displayed with appropriate labels and titles to fulfill the subtask requirements.
"""

top_10_subscribers = df.nlargest(10, 'subscribers')

plt.figure(figsize=(12, 6))
sns.barplot(x='channel_name', y='subscribers', data=top_10_subscribers, palette='viridis')
plt.title('Top 10 Channels by Subscribers')
plt.xlabel('Channel Name')
plt.ylabel('Subscribers')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

top_10_views = df.nlargest(10, 'total_views')

plt.figure(figsize=(12, 6))
sns.barplot(x='channel_name', y='total_views', data=top_10_views, palette='magma')
plt.title('Top 10 Channels by Total Views')
plt.xlabel('Channel Name')
plt.ylabel('Total Views')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Channel Creation Trend

### Subtask:
Analyze the distribution of channel creation dates to observe trends in when tech channels were established, visualized through a histogram or line plot.

To analyze the trend of channel creation, I will extract the year from the `created_date` column to create a new `creation_year` column. Then, I will count the number of channels established each year and visualize this distribution using a bar plot to observe the trends in tech channel creation over time.

**Reasoning**:
I will extract the year from the 'created_date' column, count the occurrences of each year, and then visualize this data using a bar plot to show the trend of channel creation over time.
"""

df['creation_year'] = df['created_date'].dt.year

channel_creation_trends = df['creation_year'].value_counts().sort_index()

plt.figure(figsize=(12, 6))
sns.barplot(x=channel_creation_trends.index, y=channel_creation_trends.values, palette='viridis')
plt.title('Distribution of YouTube Tech Channel Creation Years')
plt.xlabel('Creation Year')
plt.ylabel('Number of Channels')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Video Count Distribution

### Subtask:
Examine the distribution of the 'total_videos' column to understand how many videos channels typically upload, using a histogram.

**Reasoning**:
To understand the distribution of video counts, I will generate a histogram of the 'total_videos' column, ensuring it has appropriate labels and a title.
"""

plt.figure(figsize=(12, 6))
sns.histplot(df['total_videos'], bins=50, kde=True)
plt.title('Distribution of Total Videos per Channel')
plt.xlabel('Number of Videos')
plt.ylabel('Number of Channels')
plt.tight_layout()
plt.show()

"""## Country Distribution of Channels

### Subtask:
Determine and visualize the geographical distribution of the YouTube tech channels based on the 'country' column, using a bar chart for top countries.

To determine the geographical distribution of YouTube tech channels, I will first count the occurrences of each country in the 'country' column. Then, I will filter for the top 10 countries and visualize this distribution using a bar chart. This will help identify the regions with the highest concentration of tech channels. I will ensure the plot has clear labels for the x-axis (Country) and y-axis (Number of Channels), along with a descriptive title.

**Reasoning**:
Now, I will count the occurrences of each country, select the top 10, and create a bar chart to visualize their distribution, ensuring proper labels and title.
"""

country_distribution = df['country'].value_counts().nlargest(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=country_distribution.index, y=country_distribution.values, palette='plasma')
plt.title('Top 10 Countries by Number of YouTube Tech Channels')
plt.xlabel('Country')
plt.ylabel('Number of Channels')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Correlation between Metrics

### Subtask:
Calculate and visualize the correlations between 'subscribers', 'total_views', and 'total_videos' using a correlation matrix or scatter plots to understand their relationships.

**Reasoning**:
To analyze the correlations between 'subscribers', 'total_views', and 'total_videos', I will first select these columns, then calculate their correlation matrix, and finally visualize it using a seaborn heatmap with annotations.
"""

correlation_metrics = df[['subscribers', 'total_views', 'total_videos']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_metrics, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Subscribers, Total Views, and Total Videos')
plt.tight_layout()
plt.show()

"""## Final Task

### Subtask:
Summarize the key insights and findings from the comprehensive analysis of the YouTube tech channels dataset.

## Summary:

### Data Analysis Key Findings

*   **Channel Volume:** The dataset comprises 130 YouTube tech channels.
*   **Performance Distribution:** There's a wide disparity in channel performance:
    *   Subscribers range from 10,800 to 16.6 million, with a mean of approximately 512,343.
    *   Total views vary from about 26,785 to over 9 billion, averaging around 123 million.
    *   Total videos uploaded per channel range from 13 to 18,375, with a mean of 963.
    This indicates a skewed distribution with a few highly successful channels dominating the metrics.
*   **Top Channels:**
    *   **By Subscribers:** "Marques Brownlee" (16.6M), "Linus Tech Tips" (15.7M), and "Mrwhosetheboss" (15.5M) lead the pack.
    *   **By Total Views:** "Linus Tech Tips" (9.7B), "Mrwhosetheboss" (4.1B), and "Marques Brownlee" (3.9B) have the highest view counts.
*   **Creation Trend:** There was a significant boom in tech channel creation between 2007 and 2017, with a peak in 2012, 2013, 2016, and 2017 each having over 10 new channels.
*   **Video Uploads:** The distribution of total videos per channel is heavily skewed towards fewer videos, with most channels having under 1000 videos, but a long tail extending to over 18,000 videos.
*   **Geographical Distribution:** The United States dominates the YouTube tech channel landscape, followed by India, the United Kingdom, and Canada.
*   **Metric Correlations:**
    *   A strong positive correlation exists between "subscribers" and "total_views" (0.95), suggesting that channels with more subscribers generally attract more views.
    *   There is also a positive correlation between "total_videos" and both "subscribers" (0.50) and "total_views" (0.57), indicating that a higher volume of content generally contributes to more subscribers and views, though not as strongly as the subscriber-view relationship.

### Insights or Next Steps

*   The significant skew in channel performance suggests that identifying and analyzing the characteristics of top-performing channels (e.g., content strategy, upload frequency, niche) could provide valuable insights for new or growing channels.
*   The strong correlation between subscribers and total views highlights the importance of audience growth for overall channel success. Further analysis could explore specific strategies employed by top channels to gain and retain subscribers.
"""