# -*- coding: utf-8 -*-
"""ML_10_12_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfVUfU6xS9a2IrPr1rbMNTx2v047zqXB
"""

# ==============================================================================
# COURS DATA SCIENCE : CYCLE DE VIE COMPLET (SCRIPT PÉDAGOGIQUE) - DIABETES
# Auteur : Votre Professeur IA - ADAPTÉ AU DATASET DIABETES
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. IMPORTATION DES BIBLIOTHÈQUES
# ------------------------------------------------------------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Modules Scikit-Learn spécifiques
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor  # CHANGÉ pour régression
from sklearn.metrics import mean_squared_error, r2_score

# Configuration pour des graphiques plus esthétiques
sns.set_theme(style="whitegrid")
import warnings
warnings.filterwarnings('ignore')
print("1. Bibliothèques importées avec succès.\n")

# ------------------------------------------------------------------------------
# 2. CHARGEMENT DES DONNÉES DIABETES
# ------------------------------------------------------------------------------
# Chargement du dataset DIABETES (régression continue)
data = load_diabetes()

# Création du DataFrame Pandas
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target  # Progression quantitative de la maladie

print(f"2. Données DIABETES chargées. Taille : {df.shape}")
print(f"   Target : Progression quantitative de la maladie diabétique")
print(f"   Description : {data.DESCR.splitlines()[1]}\n")

# ------------------------------------------------------------------------------
# 3. SIMULATION DE "DONNÉES SALES" (5% NaN)
# ------------------------------------------------------------------------------
print("3. Introduction artificielle de valeurs manquantes (5%)...")
np.random.seed(42)
features_columns = df.columns[:-1]
df_dirty = df.copy()
for col in features_columns:
    df_dirty.loc[df_dirty.sample(frac=0.05).index, col] = np.nan

print(f"   Valeurs manquantes créées : {df_dirty.isnull().sum().sum()}\n")

# ------------------------------------------------------------------------------
# 4. NETTOYAGE ET PRÉPARATION
# ------------------------------------------------------------------------------
print("4. Nettoyage des données...")
X = df_dirty.drop('target', axis=1)
y = df_dirty['target']

# Imputation par la moyenne
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)
X_clean = pd.DataFrame(X_imputed, columns=X.columns)

print("   Imputation terminée (NaN → moyenne).")
print(f"   NaN restants : {X_clean.isnull().sum().sum()}\n")

# ------------------------------------------------------------------------------
# 5. ANALYSE EXPLORATOIRE (EDA) - ADAPTÉ DIABETES
# ------------------------------------------------------------------------------
print("5. Analyse Exploratoire (EDA)...")

# A. Statistiques descriptives
print("   Statistiques (5 premières features) :")
print(X_clean.iloc[:, :5].describe())

# B. Distribution BMI (feature clé pour diabète)
plt.figure(figsize=(10, 5))
sns.histplot(data=df, x='bmi', hue=pd.cut(df['target'], bins=3), kde=True)
plt.title("Distribution BMI selon progression diabète")
plt.xlabel("Body mass index (BMI)")
plt.show()

# C. Heatmap corrélation (10 premières)
plt.figure(figsize=(12, 8))
corr_matrix = X_clean.iloc[:, :10].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", center=0)
plt.title("Corrélation Features (Top 10) - Dataset Diabetes")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
# 6. SÉPARATION TRAIN/TEST
# ------------------------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X_clean, y, test_size=0.2, random_state=42
)

print(f"6. Séparation :")
print(f"   Train : {X_train.shape[0]} échantillons")
print(f"   Test  : {X_test.shape[0]} échantillons\n")

# ------------------------------------------------------------------------------
# 7. MODÉLISATION - Random Forest Régression
# ------------------------------------------------------------------------------
print("7. Entraînement Random Forest Regressor...")
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
print("   Modèle entraîné.\n")

# ------------------------------------------------------------------------------
# 8. ÉVALUATION PERFORMANCE (RÉGRESSION)
# ------------------------------------------------------------------------------
print("8. Évaluation performances...")

# Prédictions
y_pred = model.predict(X_test)

# Métriques régression
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"   >>> RMSE : {rmse:.2f}")
print(f"   >>> R² Score : {r2:.3f}")
print(f"   >>> Écart-type target : {y_test.std():.2f}")

# Feature importance (top 10)
importances = pd.DataFrame({
    'feature': X_clean.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False).head(10)

print("\n   Top 10 features importantes :")
print(importances)

# Visualisation prédictions vs réelles
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Valeurs réelles')
plt.ylabel('Prédictions')
plt.title('Prédictions vs Réalité (Diabetes Progression)')
plt.tight_layout()
plt.show()

# Matrice résidus
residuals = y_test - y_pred
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.scatter(y_pred, residuals, alpha=0.6)
plt.axhline(y=0, color='r', linestyle='--')
plt.xlabel('Prédictions')
plt.ylabel('Résidus')
plt.title('Résidus vs Prédictions')

plt.subplot(1, 2, 2)
plt.hist(residuals, bins=30, edgecolor='black')
plt.xlabel('Résidus')
plt.ylabel('Fréquence')
plt.title('Distribution Résidus')
plt.tight_layout()
plt.show()

print("\n--- SCRIPT DIABETES TERMINÉ ---")
print("✅ Pipeline complet : Chargement → Nettoyage → EDA → Modélisation → Évaluation")